export const NAVIGATION_STYLE_KEYS = Object.freeze(['classic', 'floating', 'dot']);

export const NAVIGATION_METRICS = Object.freeze({
  classic: {
    placement: 'attached',
    heightWithLabels: 52,
    heightIconsOnly: 48,
    horizontalMargin: 0,
    radius: 0,
    bottomGap: 0,
    rowPaddingHorizontal: 8,
    iconSize: 22,
    labelSize: 10,
    indicator: {
      type: 'line',
      width: 30,
      height: 3,
      radius: 2,
      top: 0,
    },
  },
  floating: {
    placement: 'floating',
    heightWithLabels: 58,
    heightIconsOnly: 52,
    horizontalMargin: 14,
    radius: 29,
    bottomGap: 10,
    rowPaddingHorizontal: 8,
    iconSize: 22,
    labelSize: 10,
    indicator: {
      type: 'pill',
      width: '82%',
      heightWithLabels: 42,
      heightIconsOnly: 38,
      radius: 21,
    },
  },
  dot: {
    placement: 'attached',
    heightWithLabels: 54,
    heightIconsOnly: 48,
    horizontalMargin: 0,
    radius: 0,
    bottomGap: 0,
    rowPaddingHorizontal: 10,
    iconSize: 22,
    labelSize: 10,
    indicator: {
      type: 'dot',
      size: 6,
      radius: 3,
      topWithLabels: 3,
      topIconsOnly: 36,
    },
  },
});
